runtime: node08

run: |
  source .env
  COFFEE_BIN=coffee

  if [ -z "$NODE_ENV" ] || [ "$NODE_ENV" == 'development' ]
  then
    COFFEE_BIN=./node_modules/.bin/node-dev 
  fi

  $COFFEE_BIN lib/kittyballs-web/app.coffee

run_createuser: |
  source .env
  coffee bin/user-create.coffee $ROCK_ARGS


run_createstream: |
  source .env
  coffee bin/stream-create.coffee $ROCK_ARGS
